App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']


App\Entity\Weather:
  properties:
    precipitation:
      - GreaterThan:
          value: 0
          groups: ['create', 'edit']
    windSpeed:
      - GreaterThan:
          value: 0
          groups: [ 'create', 'edit' ]